[advisories]
vulnerability = "deny"
unmaintained = "warn"
notice = "deny"
unsound = "deny"
yanked = "deny"

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "both"
unused-allowed-license = "warn"
confidence-threshold = 0.95
allow = ["Unicode-DFS-2016", "0BSD", "MirOS"]

[[licenses.exceptions]]
allow = ["MPL-2.0"]
name = "webpki-roots"

[[licenses.exceptions]]
allow = ["OpenSSL"]
name = "ring"

[[licenses.clarify]]
name = "rustls-webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
