[advisories]
yanked = "deny"

[licenses]
unused-allowed-license = "warn"
confidence-threshold = 0.95
allow = ["BSD-2-Clause", "Apache-2.0", "MIT", "Unicode-DFS-2016", "0BSD"]

[[licenses.clarify]]
name = "rustls-webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
